---
language: node_js
node_js:
  - 0.10
  - 4
  - 6
cache:
  directories:
  - node_modules
  - packages/create-inferno-app/node_modules
  - packages/inferno-scripts/node_modules
script: tasks/e2e.sh
env:
  - USE_YARN=no
  - USE_YARN=yes
